### ISSUE TITLE
`beancount-import` doesn't react to ctrl-C until the next web request

### ISSUE THREAD

**Issue by falsifian** [jbms/beancount-import#114]
This happens both with master and the version I had installed using pip (probably the latest, 1.3.3).

I press ctrl-C in the terminal once I'm done importing. But the program doesn't quit until I cause some sort of web request to be issued. For example if I go over to the Editor tab and choose a different file, that's enough for it to actually catch it.

Does this happen to anyone else?

```
falsifian moth beancount $ uname -a
OpenBSD moth.falsifian.org 6.9 GENERIC.MP#490 amd64
```

**Comment by falsifian** [comment]
Here's the Python program I use. So I guess it is `beancount_import.webserver.main` which is not being interrupted promptly.

```
# Based on https://github.com/jbms/beancount-import/blob/master/examples/manually_entered/run.py
#
# Run this with ./plugins in PYTHONPATH.

import beancount_import.webserver
import glob
import os
import sys

def run_reconcile(args):
    journal_dir = os.path.dirname(__file__)
    import_dir = os.path.join(journal_dir, "documents")
    data_sources = [
        {
            "module": "beancount_import.source.ofx",
            "ofx_filenames":
                glob.glob(
                    os.path.join(import_dir, "ofx/**/*.[oq]fx"),
                    recursive=True),
        },
        # {
        #     "module": "falsifian.from_shared_csv",
        #     "filename": os.path.join(import_dir, "from_shared.csv"),
        # },
    ]

    beancount_import.webserver.main(
        args,
        journal_input = os.path.join(journal_dir, "main.beancount"),
        ignored_journal = os.path.join(journal_dir, "ignored.beancount"),
        default_output = os.path.join(journal_dir, "misc_import.beancount"),
        open_account_output = [(".*", os.path.join(journal_dir, "accounts.beancount"))],
        balance_account_output = [(".*", os.path.join(journal_dir, "misc_import.beancount"))],
        data_sources = data_sources,
    )

if __name__ == "__main__":
    run_reconcile(sys.argv[1:])
```

**Comment by Zburatorul** [comment]
For these situations I opt for the more violent SIGHUP (Ctrl-D for me).
Don't see much  downside since beancount-import doesn't have much if any
state to write when quitting.

**Comment by falsifian** [comment]
@Zburatorul interesting! I've never heard of having a key combination for `SIGHUP`. Is Ctrl-D caught by your shell, your terminal emulator, or something else? Did you do something special to configure it?

**Comment by Zburatorul** [comment]
I don't know who handles it. It might be the terminal emulator. Didn't do anything special, just the default settings of xfce4-terminal.

**Comment by jbms** [comment]
There is SIGQUIT as well, `Ctrl-\`, which tends to be more "powerful" than `Ctrl-C`.  However, depending on your system configuration that can result in a core dump being saved, which usually isn't desired and may waste space.
