### ISSUE TITLE
Parse 'OTHERVEST' OFX INV401KSOURCE

### ISSUE THREAD

**Issue by balkjw** [jbms/beancount-import#116]
In my 401(k) OFX statements, I noticed there was a statement inside an INV401KSOURCE that was not correctly handled by beancount-import: "OTHERVEST".

Could this be added to ofx.py? I believe it just needs to be added to inv401k_account_keys, but I'm not certain.

**Comment by Zburatorul** [comment]
Hi @balkjw, thanks for bringing this up. We can definitely make this improvement. Are you willing to create a pull request? I can help you through the process if necessary.

**Comment by balkjw** [comment]
Hi @Zburatorul -- I created a pull request and tested it.
#117
