### ISSUE TITLE
Handle variations in Schwab account name format in accounts map

### ISSUE THREAD

**Issue by carljm** [jbms/beancount-import#122]
See changes removed from #120

**Comment by cookie223** [comment]
The positions csv file I got has "Positions for account Individual XXXX-1234 as of 08:42 PM ET, 08/22/2021" while the transaction csv I got has "Transactions for account XXXX-1234 as of 08/22/2021 20:42:49 ET from 07/01/2021 to 08/21/2021".
Basically we need a way to match "Individual XXXX-1234" and "XXXX-1234" to the same account. Or maybe when parsing only take out the XXXX-1234 part.

**Comment by Zburatorul** [comment]
I think we should change the `TITLE_RE` regex. I propose we do it like this:
https://regex101.com/r/DBoe1R/1

This matches all possible variations I have heard of in the discussion and does not make any new assumptions imo.

**Comment by carljm** [comment]
Yes I think that looks good, will submit a PR with that change and associated tests.

**Comment by carljm** [comment]
#123 should fix this. I didn't use your regex exactly, @Zburatorul, because positions title regex and transactions title regex still need to be a bit different due to needing to extract the date, which is in slightly different formats. But I did extract a common "account name regex" that both use, which uses your approach to extract only the `XXXX-1234` part. Your review welcome!

**Comment by carljm** [comment]
Fixed with merge of #123
