### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by witten** [jbms/beancount-import#14]
This is a feature request to support HTTPS, not in beancount-import directly, but in any reverse proxy that's wrapping it. Let me back up a bit: My use case is that I'd like to securely host beancount-import on an HTTPS web server so that both I and my partner can collaborate on processing our shared pending transactions. I realize that the typical use case is to run beancount-import locally and then connect to localhost via HTTP, but I'd prefer to run it on an actual web server if possible to aide in collaboration.

I'm wrapping beancount-import with nginx to provide the HTTPS termination, and then proxy passing requests on to the local beancount-import web server. The problem appears to be that `frontend/server_connection.ts` includes `ws://`, hard-coded:

```javascript
"ws://" + window.location.host + "/" + secretKey + "/websocket"
```

This results in a `SecurityError: The operation is insecure.` console error in Firefox when using an HTTPS URL. This is because Firefox prevents HTTPS web pages from accessing non-secured web sockets. So in this case, what I need is for the front-end to access the web socket via a secured `wss://` URL. I imagine one way to support this properly would be to fork on `ws://` or `wss://` based on the current page's protocol (HTTP or HTTPS, respectively).

Before I try to do this, I wanted to get a read on whether this is something you'd entertain. Is this use case too far outside the bounds of how you see beancount-import being used? Thanks!

**Comment by jbms** [comment]
That certainly makes sense --- I've thought about doing something similar for the same reason, but haven't attempted it.   So changes to make this work better would certainly be welcome.  If all that needs to be done is to swap wss:// for ws://, then even better.  I think more generally some other changes may be helpful to make the beancount-import webserver more convenient as a persistent, multi-user service.  For example, currently while it will reload the journal automatically there is no way to reload the import data, and failure to parse the import data often leads to terminating the program.

**Comment by witten** [comment]
Took a stab at this with the linked PR.

Agreed that some other changes may be necessary to better support multi-user. I can look into them separately as I run into each one.
