### ISSUE TITLE
Schwab: missing support for 'Pr Yr Div Revinest'

### ISSUE THREAD

**Issue by camhashemi** [jbms/beancount-import#150]
getting this error during import: `ValueError: 'Pr Yr Div Reinvest' is not a valid BrokerageAction`

seems like we can just group it with the other dividend actions

**Comment by camhashemi** [comment]
[fix here](https://github.com/jbms/beancount-import/pull/151)

**Comment by carljm** [comment]
Fixed with merge of #151. Thanks for the report and fix!

**Comment by camhashemi** [comment]
thanks for the merge @carljm. do you have any info on when this would get released?

**Comment by carljm** [comment]
I think releases are up to @jbms

**Comment by jbms** [comment]
@carljm You can feel free to release when you think is appropriate.  It just requires pushing a suitably-named tag.

**Comment by carljm** [comment]
Ok, I pushed tag `v.1.3.5` -- not sure if that somehow automatically releases to PyPI also? So far PyPI still seems to show 1.3.4 as the latest release: https://pypi.org/project/beancount-import/

**Comment by jbms** [comment]
There is a github actions workflow that automatically publishes the package to pypi, but it takes a few minutes to run.

**Comment by carljm** [comment]
Nice! New release is up now.
