### ISSUE TITLE
Examples/data/importers csv files not being imported.

### ISSUE THREAD

**Issue by hexhexd** [jbms/beancount-import#169]
Beancount 2.3.5
beancount-import 1.3.5
Trying to get my own importer to work by using the examples as an reference. I tried the run.py in both manually and fresh directory but both end up not having the entries from Examples/data/importers on the pending tab on the right. Any help would be much appreciated.

**Comment by hexhexd** [comment]
Found

**Comment by hexhexD** [comment]
https://github.com/beancount/beangulp/pull/105
