### ISSUE TITLE
High-ish idle CPU usage

### ISSUE THREAD

**Issue by witten** [jbms/beancount-import#17]
When I've got Beancount-import running, I notice that it appears to idle at around 3% (on an arbitrary machine) as viewed in `top`. This is when the front-end is not open in a browser. Just based on a cursory code inspection, my guess is that this may be due to the check for journal modifications every 100 milliseconds in `webserver.py`:

```
       self.check_modification_timer = tornado.ioloop.PeriodicCallback(
            self._check_modification, 100)
```

Is there any reason this check is so frequent? Just to get fast updates to the user?

**Comment by jbms** [comment]
There could be an option to check less frequently, but in part checking frequently is useful to avoid concurrent modification issues --- if you edit the file manually from a text editor, it is good for beancount-import to know about the changes before attempting to re-write a modified version of the file.  There is a separate check just before it actually overwrites any existing journal file, but I believe that just leads to the program terminating if that check fails.  The best solution would be to use inotify on Linux and similar APIs on other operating systems to monitor changes without polling.

**Comment by witten** [comment]
Got it, thanks for the explanation. I'll have a look at the inotify approach.
