### ISSUE TITLE
beancount-import recreates accounts

### ISSUE THREAD

**Issue by kosli** [jbms/beancount-import#179]
Every time I run beancount-import, it seems that it doesn't recognize my accounts in the open_account_output_map file. 
- I cannot choose from an existing account -> when I type a name of an existing account, it doesn't show up
- If I enter an account and confirm to create a new one -> it creates it in the accounts.beancount file
- If I run beancount-import the next time, it event doesn't recognize the accounts it created itself.

Not sure what the issue is and how to debug it?

**Comment by jbms** [comment]
Are you sure the accounts.beancount file is included from your main journal file?

**Comment by kosli** [comment]
@jbms yes, the accounts.beancount file is mentioned in my main.beancount (and fava shows the accounts correct). But I didn't realize that the "main" beancount file in beancount-import is the jounal_input -> after changing journal_input to my main.beancount it works as expected. Thank you very much for the hint in the right direction!
