### ISSUE TITLE
Fix for removal of get_feature_names in scikit-learn 1.2

### ISSUE THREAD

**Issue by hexhexd** [jbms/beancount-import#193]
AttributeError: 'DictVectorizer' object has no attribute 'get_feature_names'
> c:\users\admin\appdata\local\programs\python\python311\lib\site-packages\beancount_import\reconcile.py(139)get_prediction_explanation()
-> feature_names = classifier._vectorizer.get_feature_names()

Just use **get_feature_names_out()** and it fix the problem

**Comment by Zburatorul** [comment]
Thanks for reporting this @hexhexd.
This change has been made in master already.
