### ISSUE TITLE
Using 'e' to accept and edit causes RuntimeError: Journal file modified concurrently

### ISSUE THREAD

**Issue by philipsd6** [jbms/beancount-import#2]
I'm not sure if I'm using this correctly in a headless system via tmux. Here's how I first started `beancount-import`:

```sh
beancount-import --editor vim --journal_input personal.beancount --journal_output mint.beancount --mint_data transactions.csv --account_output '.*' accounts.beancount
```
I then see the first transaction. I want to change the name/description. So I press 'e' and nothing happens; my window is frozen. (In another session I can see that vim is running in the background.)

I tried creating a wrapper script: `tmux-vim` to launch vim in a pane instead loaded, but when I do that, since `vim` is not a child of `beancount-import`, `beancount-import` moves on to the next transaction while I change the file in the background with vim. When I save it, I end up receiving a RunTimeError on the next transaction.

**Comment by jbms** [comment]
I apologize for not seeing this issue when you posted it a long time ago.  Since then, beancount-import has been completely rewritten, and this issue no longer exists.
