### ISSUE TITLE
Request for PyPI release

### ISSUE THREAD

**Issue by btorresgil** [jbms/beancount-import#228]
Hello! I LOVE beancount-import and it's become a major part of my daily workflow. Thank you for all your hard work on this.

I'd like to request a tag on master so we can get all the latest fixes into PyPI.

Looks like it's been almost 2 years since a release to PyPI and that release is broken without the fix in #180.

I've made due by pulling master from GitHub using poetry for some time, but I recently adopted an automation tool (https://windmill.dev) that will only pull libraries from PyPI, not GitHub. So I can no longer use this workaround.

Greatly appreciate your work, thanks again!

**Comment by rodrimaia** [comment]
+1

**Comment by Zburatorul** [comment]
Can you link me to a really concise and clear set of steps on how to make a pypi release from a github repo? It'll make it more likely I get around to it.

**Comment by jbms** [comment]
We just need to push a tag and it should happen automatically via GitHub actions.

**Comment by Zburatorul** [comment]
Done.
