### ISSUE TITLE
Price Format Support

### ISSUE THREAD

**Issue by ikwtif** [jbms/beancount-import#40]
I was loading paypal data when I noticed price data doesn't take into account another format: dot before decimals (default) VS comma before decimals (drops the comma).
`XX.XX = XX.XX`
`XX,XX = XXXX` 
example: 
loaded data: `"price": "55,33\u00a0EUR"`
output: `5533 EUR`

 
This happens in `/beancount_import/amount_parsing.py` 
inside `def parse_amount(x)` 
at line 42 `number = D(m.group(2))` 
```
def parse_amount(x):
    """Parses a number and currency."""
    if not x:
        return None
    sign, amount_str = parse_possible_negative(x)
    m = re.fullmatch(r'([\$€£])?((?:[0-9](?:,?[0-9])*|(?=\.))(?:\.[0-9]+)?)(?:\s+([A-Z]{3}))?', amount_str)
    if m is None:
        raise ValueError('Failed to parse amount from %r' % amount_str)
    if m.group(1):
        currency = {'$': 'USD', '€': 'EUR', '£': 'GBP'}[m.group(1)]
    elif m.group(3):
        currency = m.group(3)
    else:
        raise ValueError('Failed to determine currency from %r' % amount_str)
    number = D(m.group(2))
    return Amount(number * sign, currency)
``` 

Is it possible to add a check for replacing `,` with `.` Not sure what the best method would be but I'm currently using this
```
    value = m.group(2)
    if ',' in value:
        value = value.replace(',','.')
    number = D(value)
```

**Comment by jbms** [comment]
It would be good to support that, but it would have to somehow be a user-specified option, I think, since unfortunately the two styles are ambiguous.  The common style in the United States is to use commas as thousands separators:

"$1,999"  = 1999 USD
"$1,999.33"  =  1999.33 USD

**Comment by TiraelSedai** [comment]
`XX.XX = XX.XX
XX,XX = XXXX`
This is a valid decimal conversion that is culture invariant and default in Python. Replacing `,` with `.` would only bring many issues.

In our country we have a comma instead of a dot as a decimal separator, so I know what I'm talking about.

What I would suggest is that you preprocess your Paypal data before feeding it into beancount-import.

**Comment by mcbloch** [comment]
Why not pass the number into the Decimal class from `beancount.core.amount` before putting it into `Amount`? The Decimal class supports numbers with comma's. 

https://github.com/beancount/beancount/blob/master/beancount/core/number.py

**Comment by moritzj29** [comment]
I ran into the same issue, check out my PR in #142 
happy for discussion 😄
