### ISSUE TITLE
Failed assertion for Fidelity accounts

### ISSUE THREAD

**Issue by scanta2** [jbms/beancount-import#47]
Importing ofx files from my Fidelity 401k account for BUY transactions is problematic. 

In ofx.py:1040 there's this assertion:
if raw.trantype in STOCK_BUY_SELL_TYPES:
                assert abs(total + fee_total +
                           (units * unitprice)) < TOLERANCE, abs(
                               total + fee_total + (units * unitprice))

The unitprice is not "correct" in the ofx file, and tolerance is not met. units and total is correct and they match the statement.

The cost_spec is computed on line 933, using unitprice, before we determine if a fee was charged. 

What I think should happen is that total and fee_total should be computed before the cost_spec initialization, and instead of using "number_per", we should use "number_total" with -(total+fee_total) as its value, and ignore potentially problematic unitprice values.

**Comment by jbms** [comment]
Would you care to create a fix and ideally also run ofx_sanitize (you may have to modify ofx_sanitize though or manually edit the result to retain important numerical values) to create a new test case that covers this?

Is the unit price in your OFX file "incorrect" because it includes the fee as part of the price?  I think that is actually the correct thing to do from an accounting perspective, but I see that is not what ofx.py currently expects.

**Comment by scanta2** [comment]
I do have a small fix that I am using on my machine.
There's no fee, I just think the unit price is rounded too much in the ofx
file itself.

**Comment by tdickman** [comment]
@scanta2 I'm running into the same issue with another provider - your [fork](https://github.com/scanta2/beancount-import/tree/FailedAssertOFX) fixed it for me perfectly. Any change you can create a PR against this version?

**Comment by scanta2** [comment]
I did create a PR but somehow it didn't pass the tests and nobody merged it.

**Comment by jbms** [comment]
Thanks again @scanta2 for your pull request.  I apologize for the long delay in responding to As might be apparent, I haven't had a lot of time to devote to this tool lately.  I just added a few comments to your pull request regarding the test failures.

If either you or @tdickman is able to provide a sanitized OFX file to serve as a test case for this issue, that would be extremely helpful.  Dealing with this type of data is unfortunately inherently pretty finicky, so having test cases is pretty critical to avoid regressions in the future.
