### ISSUE TITLE
Previously ignored balance assertions are presented for import again

### ISSUE THREAD

**Issue by Zburatorul** [jbms/beancount-import#49]
I provide a minimal example in which upon restart beancount-import presents import candidates that are already in the `ignored.journal` file. Specifically this seems to happen with balance assertions.

To reproduce:
1. run `python3 run.py`
2. repeatedly hit `i` to ignore all import candidates.
3. Ctrl-C to stop server
4. run.py again and observe same balance assertion candidate.

I have also observed this issue with price assertions. Is this nominal behaviour?
[ignore_test.tar.gz](https://github.com/jbms/beancount-import/files/4958447/ignore_test.tar.gz)

**Comment by Zburatorul** [comment]
@jbms, could you give me some pointers on where exactly the ignored transactions/balance assertions are excluded from the ones available for import? What file and method does this happen in?

**Comment by jbms** [comment]
Sorry for not getting back to you sooner.  Thanks for reporting this issue.  As you can maybe guess I haven't had a lot of time to spend on this tool lately, but I took a quick look and fixed it and added some test cases.
