### ISSUE TITLE
OFX commodity import wants to repeatedly add existing transactions

### ISSUE THREAD

**Issue by asciiphil** [jbms/beancount-import#50]
I suspect the problem is that the importer isn't looking at the right account, but I haven't had enough time to look through the code myself to see.

I have these accounts in my beancount file:

    2001-01-01 open Assets:Retirement:Employer
      ofx_org: "Vanguard"
      ofx_broker_id: "vanguard.com"
      account_id: "123456"
      ofx_account_type: "securities_and_cash"
      div_income_account: "Income:Vanguard:Dividends"
      capital_gains_account: "Income:Vanguard:Capital-Gains"
    2001-01-01 open Assets:Retirement:Employer:PreTax:VIRSX         VIRSX
    2001-01-01 open Assets:Retirement:Employer:PreTax:Cash          USD
    2001-01-01 open Assets:Retirement:Employer:Match:VIRSX          VIRSX
    2001-01-01 open Assets:Retirement:Employer:Match:Cash           USD

Here's a simple OFX file with a single transaction:

[example.zip](https://github.com/jbms/beancount-import/files/4168159/example.zip)

If I use the above account definitions with that OFX file, beancount_import wants to add the following transaction:

    2019-01-15 * "BUYMF - PRETAX"
      Assets:Retirement:Employer:PreTax:VIRSX  15.12443 VIRSX {22.18 USD}
        date: 2019-01-15
        ofx_fitid: "1141201901150022251001668EEE"
        ofx_type: "BUYMF"
      Assets:Retirement:Employer:PreTax:Cash  -335.46 USD
        ofx_fitid: "1141201901150022251001668EEE"

That's all well and good, but if I add it and then exit and restart the importer, it wants to add the transaction again even though it's already there.  (Worse, if the beancount file changes and the importer reloads it, the importer will immediately offer to re-add the same transaction.)

I would expect the importer to see that the OFX transaction already has a matching beancount transaction and not try to add it again.  It works properly with my other, cash-only accounts (a mix of bank accounts and credit cards).  The only problems are with my two retirement accounts.

**Comment by Karstographer** [comment]
I ran into this same issue. It looks like the account_leaf_regexp in ofx.py isn't identifying accounts with two sub-accounts after the base account. For example, from:
`Assets:Retirement:Employer:PreTax:VIRSX  `
it will output:
`Assets:Retirement:Employer:PreTax`
but to find the ofx_id it needs
`Assets:Retirement:Employer`

I inserted the following at line 1280 to re-run the regex on the output of the previous regex and it appeared to correctly match existing transactions and not offer to import them again:
```
if ofx_id is None and m is not None:
   m = re.fullmatch(account_leaf_regexp, m.group(1))
   lookup_account = m.group(1)
   ofx_id = account_to_ofx_id.get(lookup_account)
```

**Comment by Zburatorul** [comment]
@Karstographer, it looks like you are onto something.
I am experiencing a similar sounding issue  #49, except it occurs even with account that have a single ":" in their name.
I tried your patch, but it actually lead to a crash for me, when fullmatch() returns None. More investigation necessary.

**Comment by tdickman** [comment]
I'm running into this as well. Has anyone tried https://github.com/jbms/beancount-import/commit/5ed8b00cf0210b01443658e065318bba428c8216 to see if it fixes this?

**Comment by m-d-brown** [comment]
I believe PR #126 fixes this.

**Comment by Zburatorul** [comment]
@tdickman, can you confirm whether this issue is still present in master for you please? Otherwise we can close this.
