### ISSUE TITLE
Add payee shortcut to frontend

### ISSUE THREAD

**Issue by dumbPy** [jbms/beancount-import#64]
Just like pressing `n` allows editing narration, there should be  a "press `p` to edit/add and edit" payee.  
From the `transaction_line_editor.tsx`, I think it should be trivial given you already have `payeeStart` and `payeeEnd` indexes tracked in `TransactionLineParseResult ` and there's `editNarration` method for reference.  
That being said, I have sparingly worked on frontends and this would need a lot of effort setting up for me. :disappointed:  
Would be great if someone could add it.

**Comment by jasonhuhx** [comment]
I'll take a look at this.

**Comment by jasonhuhx** [comment]
@dumbPy @Zburatorul I've created a PR for this: https://github.com/jbms/beancount-import/pull/189

**Comment by Zburatorul** [comment]
Incredible speed @jasonhuhx. Thank you.
