### ISSUE TITLE
Feature: Accept design update PR?

### ISSUE THREAD

**Issue by mattmattmatt** [jbms/beancount-import#93]
Would you accept a PR that adds a bit of CSS here and there? This is a great tool and I appreciate the keyboard shortcuts. I'd like to give the UI a little lift – would you be interested in that?

**Comment by jbms** [comment]
Yes, I didn't put much work into the design.  If you'd like to work on it, I'd certainly be happy to accept your changes.

**Comment by mattmattmatt** [comment]
I've started to put some work into it and I'm getting close to a PR to review. There's still a good amount of details to be taken care of, but the general idea comes through [in the current state of this branch](https://github.com/jbms/beancount-import/compare/master...mattmattmatt:ui-refresh). Feel free to check it out if you're curious, and please let me know if you have any comments around changes that don't follow your vision of where this project should go.

The most notable change is that there is support for dark mode now, though most interface elements have been touched in one way or another.
